### ISSUE TITLE
Starting from SD onBeagleBone Black

### ISSUE THREAD

**Issue by rossasaurus** [syncloud/syncloud.org#14]
You sent me the pre-loaded SD for BBB.
I have read to force start from SD I hold the 'Boot' (i think) button while depowering then repowering the BBB, but all I get is 4 LEDS solid.
Also Same 4 LED's if I just start as normal, either power button or plug in power(I always use button)

What is your expected path to start SC from SD in BBB ?

Need guidance
thanks

**Comment by cyberb** [comment]
Is this still an issue?

**Comment by rossasaurus** [comment]
Hi Boris,
I gave up a long time ago.
Maybe will try next Winter when I have some time.
Thanks,
Ross

<><><><><><><><><><>

rossasaurus@gmail.com


#FreeTheBear
www.californianational.party
