### ISSUE TITLE
Suggestion to edit Mac instruction on Build Syncloud Device

### ISSUE THREAD

**Issue by fBedecarrats** [syncloud/syncloud.org#20]
Hello,
The current instruction on the [aforementioned page](https://github.com/syncloud/doc/wiki/Build-Syncloud-Device) to write the img file from a Mac terminal is:
> dd if=./[image file] of=[SD card device]

This translates into a LOOOOOOO...OOOONG writing process. I'm not very familiar with the dd command in mac, but it seems [from this forum](https://www.raspberrypi.org/forums/viewtopic.php?f=66&t=21995) that adding an argument such as *use bs=32M* or replacing */dev/disk?* by */dev/rdisk?* would significantly accelerate the process.
Best regards
FB

**Comment by cyberb** [comment]
Did you actually try one of these?
If you try them and post the results here we could update the docs.
I do not have Mac :)

**Comment by fBedecarrats** [comment]
I've just tried with *rdisk* instead of *disk* and it doesn't improve writing speed. It's been writing for 1.5 hour now, and still ongoing. So no difference with the original command.

**Comment by fBedecarrats** [comment]
Hello, it didn't work adding bs=32M (maybe because of the capital M), but with: 
> sudo dd bs=1m if=./[image file] of=[SD card device]
It was significantly faster : 26 minutes (vs. 1-2 hours the first time... I think, I didn't monitor time precisely).

**Comment by cyberb** [comment]
Apparentrly it supports only lower cases.

From the man: https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man1/dd.1.html

````
Where sizes are specified, a decimal, octal, or hexadecimal number of bytes is expected. If the number ends with a ``b'', ``k'', ``m'', ``g'', or ``w'', the number is multiplied by 512, 1024 (1K), 1048576 (1M), 1073741824 (1G) or the number of bytes in an integer, respectively. Two or more numbers may be separated by an ``x'' to indicate a product.
````

**Comment by cyberb** [comment]
Will you try 32m or I should update it 1m?

**Comment by fBedecarrats** [comment]
Thanks. I'll try 32m by the end of the week.

**Comment by cyberb** [comment]
Do you have any recommendation in the end?
