### ISSUE TITLE
Build-Syncloud-Device - Be sure to use sync with dd command

### ISSUE THREAD

**Issue by coffeehabit** [syncloud/syncloud.org#24]
from https://wiki.archlinux.org/index.php/USB_flash_installation_media#Using_dd
So
`sudo dd if=./[image file] of=[SD card device]`

should actually be
`sudo dd if=./[image file] of=[SD card device] && sync`

to verify that the dd operation has successfully completed, as it has on occasion lied to me.

e: another source
https://askubuntu.com/questions/372607/how-to-create-a-bootable-ubuntu-usb-flash-drive-from-terminal

**Comment by cyberb** [comment]
Fixed
