### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by jpma89** [syncloud/syncloud.org#25]
Hi Syncloud team,

are you interested in some German translation texts? If yes, please let me know how I can best contribute.

Thanks

**Comment by cyberb** [comment]
Yes we are interested.
Here is the example:
https://github.com/syncloud/syncloud.org/blob/master/locales/cn/translation.json

And here is the switch:
https://github.com/syncloud/syncloud.org/blob/master/js/translation.js#L32

You can fork the repo add a translation json and add a country code to translation.js.

Then you can point your browser at index.htmls and see how it works.
English is default fallback so if there is no translation in a json you will see English version.

**Comment by jpma89** [comment]
Created pull request #26

**Comment by cyberb** [comment]
Merged and available at syncloud.org, please check.

**Comment by jpma89** [comment]
Checked.
