### ISSUE TITLE
Is there anyway not to pay with paypal?

### ISSUE THREAD

**Issue by MoeSattler** [syncloud/syncloud.org#28]
I have always trouble with paypal. Is there an alternate way to pay?

**Comment by cyberb** [comment]
You can do a bank transfer to our UK account. If you want, please email support@syncloud.it for details.

Interesting, would you like us taking your card details on our site?
I always thought people trust PayPal more than just sites which take card details.

**Comment by MoeSattler** [comment]
It really depends on the vendor. I do not like paypal and had issues with them in the past. 
If I trust the vendor, I'd prefer any other payment message. Even Stripe.
